[package]
name = "hephaestus-jit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


cuda-rs = { git = "https://github.com/DoeringChristian/cuda-rs.git" }
optix-rs = { git = "https://github.com/DoeringChristian/optix-rs.git" }
thiserror = "1.0.49"
enum_dispatch = "0.3.12"
resource-pool = { git = "https://github.com/DoeringChristian/resource-pool.git" }
libloading = "0.8.0"
log = "0.4.17"
bytesize = "1.2.0"
anyhow = "1.0.75"
insta = "1.33.0"
cudarc = "0.9.14"
pest = "2.7.4"
pest_derive = "2.7.4"
bytemuck = { version = "1.14.0", features = ["extern_crate_alloc"] }
ash = { version = "0.37.3+1.3.251", features = ["linked", "debug"] }
gpu-allocator = "0.22"
