[package]
name = "hephaestus-jit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


cuda-rs = { git = "https://github.com/DoeringChristian/cuda-rs.git" }
optix-rs = { git = "https://github.com/DoeringChristian/optix-rs.git" }
thiserror = "1.0.49"
enum_dispatch = "0.3.12"
resource-pool = { git = "https://github.com/DoeringChristian/resource-pool.git" }
libloading = "0.8.0"
log = "0.4.17"
bytesize = "1.2.0"
anyhow = "1.0.75"
insta = "1.33.0"
# cudarc = "0.9.14"
bytemuck = { version = "1.14.0", features = ["extern_crate_alloc", "derive"] }
ash = { version = "0.37.3+1.3.251", features = ["linked", "debug"] }
vk-sync = { version = "0.4.0", package = "vk-sync-fork" }
gpu-allocator = "0.22"
# rspirv = { git = "https://github.com/gfx-rs/rspirv.git", version = "0.11" }
rspirv = "0.12"
inline-spirv = "0.1.6"
slotmap = "1.0.6"
itertools = "0.11.0"
pretty_env_logger = "0.5.0"
renderdoc = "0.11.0"
shaderc = "0.8.2"
tinytemplate = "1.2.1"
text_placeholder = "0.5.0"
rand = "0.8.5"
approx = "0.5.1"
paste = "1.0.14"
lazy_static = "1.4.0"
half = "2.3.1"
once_cell = "1.19.0"
indexmap = "2.1.0"

winit = "0.27.1"
raw-window-handle = "0.5"
ash-window = "0.12.0"

[dev-dependecies]
rusty-hook = "^0.11.2"

[hooks]
pre-commit = "cargo test"

[profile.release]
debug = true
