[workspace]
members = [
    "hephaestus-jit", "hephaestus-macros",
]
resolver = "2"

[workspace.dependencies]
hephaestus-jit = { path = "./hephaestus-jit" }
hephaestus-macros = { path = "./hephaestus-macros" }
