[workspace]
members = [
    "hephaestus-jit", "hephaestus-macros", "hephaestus-rust",
]
resolver = "2"

[workspace.dependencies]
jit = { path = "./hephaestus-jit", package = "hephaestus-jit" }
hephaestus-macros = { path = "./hephaestus-macros" }

mint = "0.5.9"
